Object.defineProperty(exports, "__esModule", {
    value: !0
}), exports.Api = exports.$post = exports.$get = void 0;

var e = "https://st2st2api2023.quyanedu.com/api/", _ = "https://st2st2api2023.quyanedu.com/api/", m = {
    domain: "https://st2st2api2023.quyanedu.com/uploads/img/",
    GET: {
        big_book: _ + "index/big_book",
        big_chapter: _ + "index/big_chapter",
        big_subject_info: _ + "index/big_subject_info",
        big_edit_subject_log: _ + "member/big_edit_subject_log",
        big_qualifications: _ + "member/big_qualifications",
        my_info: _ + "member/get_member_info",
        book_list_all: _ + "index/book_list_all",
        subject_ids_3e: _ + "index/subject_ids_3e"
    }
};

exports.Api = m;

var r = {
    library_discipline: "index/discipline",
    getopenid: "login/login",
    login: "login/user_info",
    member_info: "member/get_member_info",
    get_show: "index/get_show",
    library_class: "index/library_class",
    library_list: "index/library_list",
    big_chapter: "index/big_chapter",
    big_qualifications: "member/big_qualifications",
    my_library: "member/my_library",
    add_my_library: "member/add_my_library",
    add_all_library: "member/add_all_library",
    del_all_library: "member/del_all_library",
    library_index_list: "index/library_index_list",
    again_subject: "member/again_subject",
    rand_subject: "member/rand_subject",
    subject_info: "index/subject_info",
    subject_ids: "index/subject_ids",
    comment_list: "index/comment_list",
    give_log: "member/give_log",
    comment_add: "member/comment_add",
    note_list: "index/note_list",
    note_add: "member/note_add",
    note_my_list: "member/note_my_list_1",
    note_my_list_down: "member/get_list_export",
    upload_img: "tx_autoload/upload_file",
    report_errors: "member/report_errors",
    get_member_info: "member/get_member_info",
    share_statistics: "member/share_statistics",
    library_all_list: "index/library_all_list",
    note_del: "member/note_del",
    amount_log_1: "member/amount_log_1",
    note_info: "index/note_info",
    note_edit: "member/note_edit",
    get_share: "index/get_share",
    apply_amount: "member/apply_amount",
    amount_log_2: "member/amount_log_2",
    note_my_id: "member/note_my_id",
    make_question: "member/make_question",
    make_wrong_log: "member/wrong_logs",
    make_wrong_logs: "member/wrong_logss",
    wrong_log_library: "member/wrong_log_library",
    wrong_log_chapter: "member/wrong_log_chapter",
    course_list: "index/course_list",
    card_subject: "member/card_subject",
    qrcode: "index/qrcode",
    my_team: "member/my_team",
    my_team_list: "member/my_team_list",
    examination: "member/examination",
    get_mock_list: "index/get_mock_list",
    examination_mock_paperInfo: "index/examination_mock_paperInfo",
    examination_mock: "member/examination_mock",
    mock_subject_info: "index/mock_subject_info",
    mock_make_question: "index/mock_make_question",
    mock_winding: "index/mock_winding",
    mock_result: "index/mock_result",
    mock_cxks: "index/mock_cxks",
    mock_ranking_list: "index/mock_ranking_list",
    print_wrong: "index/print_wrong",
    seach_cont: "index/seach_cont",
    mock_wrong_log_my: "member/mock_wrong_log_my",
    get_mock_wrong_num: "member/get_mock_wrong_num",
    getLibraryInfo: "index/getLibraryInfo",
    getTestPaperFormationSubjectIds: "index/getTestPaperFormationSubjectIds",
    member_news: "member/member_news",
    update_member: "member/update_member",
    update_weixin_member: "member/update_weixin_member",
    subject_statistics_log: "member/subject_statistics_log",
    member_news_num: "member/member_news_num",
    wrong_log_my: "member/wrong_log_my",
    get_banner: "index/get_banner",
    activation_code: "member/activation_code",
    get_sign_list: "member/get_sign_list",
    add_sign: "member/add_sign",
    wrong_log_del: "member/wrong_log_del",
    wrong_log_add: "member/wrong_log_add",
    share_list: "index/share_list",
    library_index: "index/library_index",
    library_target: "member/library_target",
    decryption: "login/decryption",
    pay_library: "member/pay_library",
    ranking_list: "index/ranking_list",
    goods_list: "index/goods_list",
    goods_info: "index/goods_info",
    default_goods_address: "member/default_goods_address",
    add_goods_order: "member/add_goods_order",
    cancel_goods_order: "member/cancel_goods_order",
    my_goods_order: "member/my_goods_order",
    info_goods_order: "member/info_goods_order",
    confirm_goods_order: "member/confirm_goods_order",
    download_goods_order: "member/download_goods_order",
    integral_meal: "index/integral_meal",
    pay_integral_meal: "member/pay_integral_meal",
    list_goods_address: "member/list_goods_address",
    goods_address_default: "member/goods_address_default",
    del_goods_address: "member/del_goods_address",
    add_goods_address: "member/add_goods_address",
    edit_goods_address: "member/edit_goods_address",
    add_screenshot: "member/add_screenshot",
    wrong_log_course_1: "member/wrong_log_course_1",
    wrong_log_library_1: "member/wrong_log_library_1",
    wrong_log_del_1: "member/wrong_log_del_1",
    mk_question_list: "member/mk_question_list",
    mk_question_info: "member/mk_question_info",
    mk_to_exchange: "member/mk_to_exchange",
    mk_pay_question: "member/mk_pay_question",
    mk_up_share_log: "member/mk_up_share_log",
    mk_generate_sheet: "member/mk_generate_sheet_new",
    mk_sheet_info: "member/mk_sheet_info",
    mk_subject_info: "member/mk_subject_info",
    mk_submit_subject: "member/mk_submit_subject",
    mk_submit_subject_big: "member/mk_submit_subject_big",
    mk_submit_member_report: "member/mk_submit_member_report",
    mk_answer_statistics: "member/mk_answer_statistics",
    mk_sort_top: "member/mk_sort_top",
    add_mk_line: "index/add_mk_line",
    sys_chat_img: "index/get_share_img"
};

exports.$get = r;

var o = {
    report_add: "/member/report_add",
    mock_log_add: "/index/mock_log_add"
};

for (var i in exports.$post = o, r) r[i] = e + r[i];

for (var t in o) o[t] = e + o[t];